#!/bin/bash

# RUN BLASTP FOR PROTEINS PREDICTED BY PRODIGAL
# This script loops through Prodigal outputs for all samples,
# runs BLASTP against a custom symbiosis gene database,
# and saves results as tab-separated files.
# Missing protein files are logged separately.

# PATHS
# Directory containing Prodigal outputs for each sample
PRODIGAL_DIR="./prodigal_outputs"

# BLAST database to search against
BLAST_DB="./symbiosis_all_genes_max1000"

# Directory to store BLAST output files
OUTPUT_DIR="./blast_output_1"

# PARAMETERS
# Number of threads for BLAST
NUM_THREADS=24

# File to log samples missing protein files
MISSING_FILE="$OUTPUT_DIR/missing_protein_files.txt"

# SETUP
# Create output directory if it does not exist
mkdir -p "$OUTPUT_DIR"

# Clear previous missing file log
> "$MISSING_FILE"

# LOOP OVER SAMPLES
# Each sample has its own folder in Prodigal outputs
for sample_dir in "$PRODIGAL_DIR"/* ; do
    # Extract sample name from directory
    sample_name=$(basename "$sample_dir")

    # Protein FASTA file generated by Prodigal
    prot_file="$sample_dir/${sample_name}_proteins.faa"

    # Output BLAST tabular file
    output_file="$OUTPUT_DIR/${sample_name}_blast.tsv"

    # Check if protein file exists
    if [[ -f "$prot_file" ]]; then
        echo "Running BLAST for sample: $sample_name"

        # Run BLASTP
        blastp \
          -query "$prot_file" \
          -db "$BLAST_DB" \
          -out "$output_file" \
          -evalue 1e-5 \
          -outfmt "6 qseqid sseqid pident length qlen slen evalue bitscore" \
          -num_threads "$NUM_THREADS"

    else
        # Log missing protein file
        echo "$sample_name missing protein file" | tee -a "$MISSING_FILE"
    fi
done

# FINISHED
echo "All BLAST jobs completed."
echo "Missing protein files (if any) are listed in $MISSING_FILE"